on:
  workflow_dispatch:
    inputs:
      environment-selection:
        description: "Choose the environment you want to deploy to."
        required: true
        default: staging
        type: choice
        options:
          - staging
          - dev
          - QA
          - production
          
      

jobs:
  deploy-approved:
    runs-on: ubuntu-latest

    steps:
      - name : check manual trigger
        run: echo "manual trigger is activated."
